### ISSUE TITLE
CMI 9 / Java 16 / Paper 1.17.1 / EssentialsX New storage system

### ISSUE THREAD

**Issue by mrfloris** [BlackBeltPanda/Essentials-Kits-To-CMI#1]
Hey there,

I notice this is over a year old now, and we've moved on a bit. Just checking if this is still valid for the latest 1.17.1 with java 16, and the latest CMI 9 and EssentialsX, because I think essx has moved to a new way of storing user data. 

As a courtesy (someone pointed it out) I've included this tool in my github FAQ page for cmi, and was curious if this is still valid with all the new stuff/versions. 

Thanks in advance,

**Comment by BlackBeltPanda** [comment]
Yes, I can confirm the plugin still works. I went ahead and updated it for the latest versions of EssentialsX and CMI, as well as MC 1.17, just in case. The old version should still work, but v1.1 is tested working.

**Comment by mrfloris** [comment]
Awesome, thank you. I will keep it linked [here](https://github.com/mrfdev/CMI/blob/master/Resources/FAQ/cmi-import.md).
